title: "Pedro Pardal"
baseURL: "https://www.ppardalj.com/"
languageCode: "es-es"
theme: "ananke"

MetaDataFormat: "yaml"
DefaultContentLanguage: "es"
SectionPagesMenu: "main"
pagination:
  pagerSize: 6
googleAnalytics: "UA-150818815-1"
enableRobotsTXT: true
disqusShortname: "ppardalj"

disableKinds:
  - taxonomy
  - term

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

params:
  description: "Soy consultor, formador y desarrollador de software."
  background_color_class: "bg-black"
  recent_posts_number: 2
  ananke:
    social:
      follow:
        networks:
          - linkedin
          - youtube
          - instagram
      linkedin:
        username: ppardalj
        profilelink: "https://www.linkedin.com/in/ppardalj/"
      youtube:
        username: ppardalj
      instagram:
        username: ppardalj
